# Site
name: "Koii"
description: Koii keep track of what's on the web. Try today.
logo: "assets/images/goldfish.svg"
favicon: "assets/images/goldfish.svg"
baseurl: ""
disqus: "disqus_BSQKXyVFLL"
email: "services@koii.network"
mailchimp-list: "http://eepurl.com/he-SCz"

include: ["_pages"]
permalink: /:title/

# SEO
twitter:
  username: KoiiNetwork
  image: "/assets/images/WELCOMEFINNIE_TWITTTERBLOG.png"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  sal:
    name: Sal
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar1.jpg
    bio: "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet

  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
