# Site
name: "Koii"
description: Koii keep track of what's on the web. Try today.
favicon_ico: "/favicon.ico"
favicon_png: "/favicon.png"
url: "https://www.koii.network"
disqus: "disqus_BSQKXyVFLL"
email: "services@koii.network"
mailchimp-list: "http://eepurl.com/he-SCz"

include: ["_pages"]
permalink: /:title/

# SEO
twitter:
  username: KoiiFoundation
  image: "/assets/images/WELCOMEFINNIE_TWITTTERBLOG.png"

discord:
  invite: "https://discord.gg/koii-network"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
