---
layout: post
title: "Koii is Swimming With NEAR"
categories: [Announcement]
image: assets/images/blog/Koii-near.png
---

### The Koii Network’s new partnership with NEAR is founded on a mutual desire to create an open internet for all. 

Our united ethos in several key areas will make this a beneficial integration for both protocols:

-Decentralization focused

-Dedication to an open and permissionless internet

-User first & self-sovereign

-Building tools that enable programmable ownership

-A strong belief that the future of web3 will be cross-chain


We are excited to integrate NEAR with our core products on Koii Network, while also providing access to our unique set of tools to those building with NEAR protocol. This integration will provide greater utility and flexibility to users of both networks while enhancing our developer toolkits. Through wallet integrations, NEAR-based tokens and NFTs will be compatible with the Finnie wallet and K2 Settlement Layer. 

Koii-X UI templates will also benefit from NEAR integration. Soon, you can use NEAR as a payment option for any site you build using a Koii-X template, including the recently released crowdfunding portal. As the integration progresses, we will be expanding the utility of Koii nodes to support NEAR tooling, opening up many possibilities for applications and services in the *near* future.

To fully appreciate the potential of this partnership let's take a closer look at what the Koii Network is and how it works.
 

## What Makes Koii Unique

Koii Network is a protocol focused on building the tools and infrastructure needed to decentralize and open the internet. What sets Koii apart from other networks is its focus on attention. Koii’s unique toolset is designed to help developers and creators permanently own their content and fully benefit from the attention the content generates.

Koii does this by tracking and rewarding the attention that registered content receives across the internet. As a result, the protocol is able to monetize attention without requiring a creator or developer to give up ownership rights or worry about arbitrary changes to a platform’s monetization policies. Attention tracking also works to incentivize a network of lightweight chain-agnostic Koii Nodes that provide fast and inexpensive ways to build, run, and deploy decentralized apps (“dApps”) untethered to any specific blockchain.

## How does Koii Incentivize Quality Content?

As a network layer, Koii is designed to interact with multiple blockchains on behalf of the network. The protocol manages internal consensus using a stake-based approach called Proofs of Real Traffic (PoRT). This consensus process allows Koii to track and verify traffic (“attention”) across content gateways, which links daily KOII token distribution to traffic volume, creating direct incentives for content creation. 

In practice, this means that PoRT yields daily KOII proportional to the verified attention generated by NFT creators, developers, artists, musicians, cinematographers, web designers, podcasters, really ANYONE who takes part in the attention economy. Each time content receives views, comments, likes, or follows, the creator (or owner) mines new KOII tokens.

## Interacting and Building with Koii

How can you get a feel for what the Koii protocol is capable of? If you’re a creator and would like to experience Koii, the easiest way is to download and install the Finnie wallet browser extension. From there you will be able to register and manage your content, mint an Atomic NFT, create a Decentralized Identity (Koii DID), manage your Arweave and Ethereum Keys, earn attention rewards, and even send and receive Koii tokens. 

If you are a developer looking to leverage the Koii tech stack, you can do so through the Koii SDK and Koii-X UI template library. The templates are built in 100% Javascript and are designed to help developers of all skill levels build and deploy applications quickly and easily. To see just how easy the process can be, take a look at a step-by-step tutorial on how to deploy your own crowdfunding portal in 10 minutes using Koii-X.

## Koii X NEAR Partnership

While this is a general and not an exhaustive overview of Koii Network we wanted to highlight its unique attributes and the value it brings to the partnership. As was mentioned at the outset - both Koii and NEAR have very closely aligned philosophies when it comes to the future of the internet. The potential to seamlessly leverage the unique attributes of each will be an extremely enticing value proposition to both creators and developers. We are excited to see the applications that emerge from these next-gen protocols.


[Check us out](http://koii.me/u/koii){:target="\_blank"} and follow our socials to keep up to date with the latest developments

Twitter: [@KoiiNetwork](https://twitter.com/KoiiNetwork){:target="\_blank"}<br/>
Telegram: [t.me/koiinetwork](http://t.me/koiinetwork){:target="\_blank"}<br/>
LinkedIn: [Koii Network](https://www.linkedin.com/company/koii-network/mycompany/){:target="\_blank"}<br/>
